### ISSUE TITLE
Issue with jquery-ui-effect (Magento 2.4.4)

### ISSUE THREAD

**Issue by Amadeco** [magesuite/magepack#140]
Edit 03/05/2022 : 
Just remove the two files from the magepack.config.js to solve the issue...

Good afternoon,

I have a situation with your wonderful extension and the new released magento 2.4.4 version.
Indeed, the two files from jquery-ui updated framework :

1. [lib/web/jquery/ui-modules/effects/effect-fade.js](https://github.com/magento/magento2/blob/2.4-develop/lib/web/jquery/ui-modules/effects/effect-fade.js)
2. [lib/web/jquery/ui-modules/effects/effect-blind.js](https://github.com/magento/magento2/blob/2.4-develop/lib/web/jquery/ui-modules/effects/effect-blind.js)

Which were reworked from the previous version, throws an error only when I magepack them (with the standard minification and bundle I do not have any issue).

This is the error I have in my developer console for the homepage : 
`Uncaught Error: Mismatched anonymous define() module: function($){"use strict";return $.effects.define("fade","toggle",(function(e,t){var n="show"===e.mode;$(this).css("opacity",n?0:1).animate({opacity:n?1:0},{queue:!1,duration:e.duration,easing:e.easing,complete:t})}))}`

This error is also throwed by blind effect.

So far, I can either remove them from the magepack.config.js (requirejs we will download them as standalone version) or correct them manually by naming them.

Exemple for effect-fade.js : 
```

/*!
 * jQuery UI Effects Fade 1.13.0
 * http://jqueryui.com
 *
 * Copyright jQuery Foundation and other contributors
 * Released under the MIT license.
 * http://jquery.org/license
 */

//>>label: Fade Effect
//>>group: Effects
//>>description: Fades the element.
//>>docs: http://api.jqueryui.com/fade-effect/
//>>demos: http://jqueryui.com/effect/

( function( factory ) {
	"use strict";

	if ( typeof define === "function" && define.amd ) {

		// AMD. Naming the module
		define('jquery-ui-effect-fade', [
		// AMD. Register as an anonymous module.
		//define( [
			"jquery",
			"../version",
			"../effect"
		], factory );
	} else {

		// Browser globals
		factory( jQuery );
	}
} )( function( $ ) {
"use strict";

return $.effects.define( "fade", "toggle", function( options, done ) {
	var show = options.mode === "show";

	$( this )
		.css( "opacity", show ? 0 : 1 )
		.animate( {
			opacity: show ? 1 : 0
		}, {
			queue: false,
			duration: options.duration,
			easing: options.easing,
			complete: done
		} );
} );

} );

```

These two JS files are used for : 

- fade.js for minicart
- blind.js for message 

a Pull Request advice to suppress them for the native code of Magento for native CSS Transition and native function from jQuery itself : [https://github.com/magento/magento2/pull/32886](https://github.com/magento/magento2/pull/32886)

Not sure if this error come from our current configuration as it heavy customized,

Did you meet this issue also on Magento 2.4.4 ?

Magento 2.4.4 have also a mapping error for Magento_Theme module (which is not related to my current issue) : 
[https://github.com/magento/magento2/issues/35327](https://github.com/magento/magento2/issues/35327)

**Comment by gwharton** [comment]
generate
sed --in-place -e "/jquery\/ui-modules\/effects\/effect-fade/d" magepack.config.js
sed --in-place -e "/jquery\/ui-modules\/effects\/effect-blind/d" magepack.config.js
bundle

**Comment by leonhelmus** [comment]
@NathanDayFE This resolved my issue i had with 2.4.4 :)

**Comment by leonhelmus** [comment]
@gwharton I also needed to remove both jquery/ui-modules/effects/effect-fade & /jquery/ui-modules/effects/effect-blind from the magepack.config.js. How did you resolve that?

**Comment by leonhelmus** [comment]
@NathanDayFE  I also needed to have https://github.com/magento/magento2/pull/32886 to resolve the checkout issue we talked about.

**Comment by domeglic** [comment]
I ran into the same issue, but the patch provided by @NathanDayFE didn't quite work. I had to use different module names needed instead ([patch](https://gist.github.com/domeglic/305f299372277d1a95d7dc587fa0f0bb))

Outside of checkout you don't see much wrong, but requirejs actually fails to load all dependencies because the effects modules don't load. You can type "require.s.contexts._.registry" in the console and check that some of the modules have depCount higher than 0, meaning those dependencies didn't yet load. 

But in checkout the loader is only removed when requirejs finishes, which is why it is more apparent. The jquery effects need to be named correctly otherwise I guess they aren't found (I don't know much about requirejs)

Another solution that worked for me is what @gwharton suggested, to remove the effects from the magepack config. 

Also I thought the PR #142 should have fixed this but it doesn't.

**Comment by Amadeco** [comment]
I am using these repositories to remove the jQuery effect from Magento :

https://github.com/vasilii-b/magento2-frontend-improvements
(I found this one also : https://github.com/magesuite/magento-patches)

**Comment by jeremycharron** [comment]
Is there any official plan from the Magepack team to update this module? We have several projects internally that are waiting for support for Adobe Commerce 2.4.4 and 2.4.5.  

One of our team tried suggested solutions in this thread without success.

**Comment by josepaitamala** [comment]
Also having issues here with Magepack and Magento 2.4.4, first with my old bundle files, I was getting a lot of `TypeError: $.widget is not a function` errors on Checkout page for all JS widget files that didn't have 'jquery-ui-modules/widget' as a dependency, if I go and added manually this dependency to each file then the checkout page would work, but I thought this would be tedious to create a patch for every single JS widget file to include 'jquery-ui-modules/widget' as a dependency. Another thing I noticed is that when trying to create a new magepack.config.js file, the paths for jquery files had changed from what it used to be `'jquery-ui-modules/widget': 'jquery/ui-modules/widget'` into `'jquery/ui-modules/widget': 'jquery/ui-modules/widget'` and then no JS was working but no error was showing in the console either, I don't know if the issue has something to do with this change of path naming maybe? But at the end the only way I could fix everything was by removing every jquery file from the magepack.config.js  file. Any light to fix this Magepack and Magento 2.4.4 incompatibility  would be appreciate it.

**Comment by fredden** [comment]
The mapping of `jquery-ui-modules/widget` to `jquery/ui-modules/widget`, still exists in the latest version of Magento: https://github.com/magento/magento2/blob/2.4.5/app/code/Magento/Theme/view/base/requirejs-config.js#L47 (and in 2.4.4)
I don't know why magepack wouldn't have identified these mappings properly. If this is causing you difficulty, please can you raise a new issue with details of this error so this can be investigated properly.

If a JavaScript file doesn't correctly specify its dependencies then setting up magepack will often highlight this. This should be fixed in the JavaScript file itself, not in magepack. If these issues are showing up in core Magento code, I'll happily open pull requests to get these solved; please let us know what files are causing you difficulty so we can help identify the vendor to which you can report these errors. If it's your own code, then you'll need to specify your dependencies.

**Comment by fredden** [comment]
@josepaitamala my best guess is that something else loads these files on the page before your code runs. Thanks for confirming this is a duplicate of #140.

**Comment by rhoerr** [comment]
Based on a site running 2.4.5-p1, ui-modules/core may also trigger the anonymous define issue.

```diff --git a/lib/web/jquery/ui-modules/core.js b/lib/web/jquery/ui-modules/core.js
index 231a4e6..539fded 100644
--- a/lib/web/jquery/ui-modules/core.js
+++ b/lib/web/jquery/ui-modules/core.js
@@ -2,7 +2,7 @@
 ( function() {
 "use strict";

-define( [
+define('jquery/ui-modules/core', [
 	"jquery",
 	"./data",
 	"./disable-selection",
```

**Comment by niihal** [comment]
please add steps how to apply it on ECE

**Comment by fredden** [comment]
@niihal apply what, where? This bug has been fixed in magepack. Please check you're using the latest version of magepack (the tool, not the Magento module).

**Comment by amcguireweb** [comment]
> @niihal apply what, where? This bug has been fixed in magepack. Please check you're using the latest version of magepack (the tool, not the Magento module).

How would we make sure "we're using the latest version of magepack" on Adobe Commerce Cloud? We just updated to 2.4.6-p3 from 2.4.3 and are now experiencing these errors on checkout. We didn't experience them on 2.4.3 prior to updating.

$.effects.define is not a function

**Comment by fredden** [comment]
@amcguireweb that depends entirely on how you've set up your build steps for Cloud. If you're using something like this https://github.com/magesuite/magepack/issues/135#issuecomment-1050793036 then I'd expect you are already using the latest version. You can print out the version by running `magepack --version`. The latest version at time of writing is `2.11.2`. https://github.com/magesuite/magepack/tags

**Comment by nabeelfocus** [comment]
We just updated to 2.4.6-p2 from 2.4.5-p1 and are now experiencing these errors on checkout minicart not update.i using latest magepack version 2.11.2.but the minicart has no content and doesn't update. When I refresh the page, the minicart still doesn't show it's content and it's count. When I proceed to the product page, everything is showing just fine.
